git:
  depth: 1

language: php

php:
  - '7.1'

before_install:
  - phpenv config-rm xdebug.ini
  - mkdir -p build/logs

install:
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php --version=1.3.2
  - php -r "unlink('composer-setup.php');"

script:
  - ./vendor/bin/phpunit

notifications:
    on_success: never
    on_failure: always